### ISSUE TITLE
没有行情数据，无法下单委托

### ISSUE THREAD

**Issue by nirvanalinlei** [veighna-global/vnpy_mt5#4]
安装vnpy 社区版3.9.0，以及vnpy_mt5后，按照本模块说明编译mql5和设置好EA，带MT5模块运行vnpy trader后，在交易窗口里，输入EURUSD回车，没有出现行情数据。

试图进行交易EURUSD 多开 0.1手市价，出现错误如下：
Traceback (most recent call last):
  File "D:\veighna_studio\lib\site-packages\vnpy\trader\ui\widget.py", line 991, in send_order
    self.main_engine.send_order(req, gateway_name)
  File "D:\veighna_studio\lib\site-packages\vnpy\trader\engine.py", line 188, in send_order
    return gateway.send_order(req)
  File "D:\veighna_studio\lib\site-packages\vnpy_mt5-5.0.0-py3.10.egg\vnpy_mt5\mt5_gateway.py", line 181, in send_order
    result: bool = packet["data"]["result"]
KeyError: 'data'

**Comment by veighna-global** [comment]
Please try the new VeighNa Evo version to see if the problem is solved.
